variable "dev_rg" {}
variable "dev_vnet" {}
variable "dev_subnet" {}
variable "dev_nic" {}
variable "dev_vms" {}
variable "dev_nsg" {}
variable "dev_nsg_allocation" {}
variable "dev_pip" {}
variable "dev_bastion" {}