variable "dev_rg" {}
variable "dev_vnet" {}
variable "dev_subnet" {}
variable "dev_nic" {}
variable "public_ip" {}
variable "dev_bastion" {}
variable "dev_vms" {}
variable "nsg" {}
variable "devassonsg" {}
variable "lb_details" {}
variable "lbnic_details" {}